baseURL = 'https://ghassbomb.github.io/'
languageCode = 'en-us'
title = 'Ghassan Shahzad'
theme = 'minblog'
disqusShortname = "ghassan-shahzad"
googleAnalytics = 'G-DLSVNLVBTV'
staticDir = ["static"]

[params]

dateFormat = "January 2, 2006"
showWordCount = true
showReadingTime = true
since = "2023"
description = 'Tanto buon che val niente.'

[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[frontmatter]
date = ['date']
publishDate = ['publishDate']

[markup.goldmark.renderer]
unsafe = true

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5

[params.author]
name = "Ghassan Shahzad"
location = "Lahore"

[markup.tableOfContents]
endLevel = 5
startLevel = 2
