baseURL = "https://ghassbomb.github.io/"
languageCode = "en-us"
title = "Ghassan Shahzad"
canonifyurls = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[markup.goldmark.renderer]
unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'