baseURL = "https://ghassbomb.github.io/"
languageCode = "en-us"
title = "Ghassan Shahzad"
theme = "ananke"

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Books"
url = "/books"
weight = 2

[[menu.main]]
name = "Philosophy"
url = "/philosophy"
weight = 3

[[menu.main]]
name = "Mathematics"
url = "/mathematics"
weight = 4

SectionPagesMenu = "posts"

[markup.goldmark.renderer]
    unsafe = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Ghassan Shahzad"
favicon = "/favicons/favicon.ico"
site_logo = ""
featured_image_class = "cover bg-top"
cover_dimming_class = "bg-black-60"
description = "Hobbies: reading, wargaming, jazz, mathematics, and some other stuff. That's what I write about."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-navy"
recent_posts_number = 5