baseURL = "https://ghassbomb.github.io/"
languageCode = "en-us"
title = "Ghassan Shahzad"
theme = 'nostyle'
canonifyurls = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      KaTeX = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rrt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  [params.theme_config]
    appearance        = "auto"
    back_home_text    = "<-"
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true